// <auto-generated />
namespace CompetitionFisher.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addindexesauth0UserId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addindexesauth0UserId));
        
        string IMigrationMetadata.Id
        {
            get { return "201707160530120_add-indexes-auth0UserId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
